name: functional-tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      UPLOAD_UPDATED_EXPECTED_RESULTS:
        description: 'Set this to true to upload updated golden file expected results and upload these results as a Github workflow artifact.'
        required: false
        default: true
      UPLOAD_KUBERNETES_DEBUG_INFO:
        description: 'Set this to true to collect the debug info of the k8s cluster and upload this info as a Github workflow artifact.'
        required: false
        default: true

env:
  GO_VERSION: 1.23.6
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
jobs:
  get-test-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get matrix
        id: test_matrix
        run: |
          echo "Getting test matrix"
          matrix=`cat ci-matrix.json | jq '.functional_test_v2' | jq -r 'tostring' | tr -d '\n'`
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.test_matrix.outputs.matrix }}

  kubernetes-test:
    env:
      KUBECONFIG: /tmp/kube-config-splunk-otel-collector-chart-functional-testing
      KUBE_TEST_ENV: kind
      UPLOAD_UPDATED_EXPECTED_RESULTS: ${{ github.event.inputs.UPLOAD_UPDATED_EXPECTED_RESULTS || 'false' }}
      UPLOAD_KUBERNETES_DEBUG_INFO: ${{ github.event.inputs.UPLOAD_KUBERNETES_DEBUG_INFO || 'false' }}
    needs: get-test-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-test-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'Ignore Tests') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '**/go.sum'
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:${{ matrix.k8s-kind-version }}
          kubectl_version: ${{ matrix.k8s-kind-version }}
          cluster_name: kind
          config: ./.github/workflows/configs/kind-config.yaml
      - name: Fix kubelet TLS server certificates
        run: |
          kubectl get csr -o=jsonpath='{range.items[?(@.spec.signerName=="kubernetes.io/kubelet-serving")]}{.metadata.name}{" "}{end}' | xargs kubectl certificate approve
      - name: Update dependencies
        run: |
          make dep-update
      - name: run functional tests
        id: run-functional-tests
        env:
          K8S_VERSION: ${{ matrix.k8s-kind-version }}
        run: |
          TEARDOWN_BEFORE_SETUP=true UPDATE_EXPECTED_RESULTS=${{ env.UPLOAD_UPDATED_EXPECTED_RESULTS }} SUITE=${{ matrix.test-job }} make functionaltest
      - name: Collect Kubernetes Cluster debug info on failure
        if: always() && (steps.run-functional-tests.outcome == 'failure' || env.UPLOAD_KUBERNETES_DEBUG_INFO == 'true')
        id: collect-debug-info
        run: |
          echo "Functional tests failed. Collecting debug info for current state of the Kubernetes cluster..."
          cd tools
          ./splunk_kubernetes_debug_info.sh
      - name: Upload Kubernetes Cluster debug info
        if: always() && (steps.run-functional-tests.outcome == 'failure' || env.UPLOAD_KUBERNETES_DEBUG_INFO == 'true')
        uses: actions/upload-artifact@v4
        with:
          name: k8s-debug-info-${{ matrix.test-job }}-${{ matrix.k8s-kind-version }}
          path: tools/splunk_kubernetes_debug_info_*
          retention-days: 5
      - name: Upload test results
        if: always() && env.UPLOAD_UPDATED_EXPECTED_RESULTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: functional_tests-${{ matrix.test-job }}-${{ matrix.k8s-kind-version }}
          path: functional_tests/results
          retention-days: 5